### ISSUE TITLE
Add some kind of date to posts

### ISSUE THREAD

**Issue by passcod** [arzg/website#1]
Hi! Liked the fjord post. Could you consider adding some kind of date displayed on the posts? I had a thought about it but wanted to check if it was recent enough before doing anything (little point suggesting something about a years old post)... fetching the git history to figure out when the post was written is pretty suboptimal though

**Comment by lunacookies** [comment]
Glad you liked the post 😄

> Could you consider adding some kind of date displayed on the posts?

Yep, that’s a good idea; I’ve been planning to add this. Thanks for reminding me I guess :)
