### ISSUE TITLE
Bring RSS back?

### ISSUE THREAD

**Issue by LucasFA** [arzg/website#15]
Hi Luna!

It's always a pleasure to read your posts! I was setting up my RSS feed and I think you don't have - not anymore anyway, seeing https://github.com/lunacookies/blog/commit/f26070b2fa0ccdd9bc16a394b6baf571a27dd626. I figure you were moving your posts into another page (maybe? IDK) but have been writing for a while here now.

Anyway, if - and only if - it is not too much trouble, I'd love to have your blog in RSS! I would _hope_ it's reverting the commit and not _too_ much more but I have honestly no idea how it works.

Edit: seems I just missed the proper link! [blog.xoria.org/index.xml](https://blog.xoria.org/index.xml). I had tried a few but not this one. Oh well. I'll close then.

**Comment by lunacookies** [comment]
Hi, and thank you for the compliments :)

I actually didn’t realize that Hugo was already generating an RSS feed for my blog. Sadly it seems that it only includes the first paragraph of text and strips all formatting from it. (This sounds a lot like Hugo’s `.Summary`? Anyway.)

I’ll go and try setting up a proper RSS feed, though that didn’t go super well last time. Maybe this is the push I need to finally make my own static site generator :P

**Comment by LucasFA** [comment]
Nice, works better. Thank you!
>Maybe this is the push I need to finally make my own static site generator :P

Would be meta to publish a Writing a SSG blog series in the newly written SSG, ha!
