### ISSUE TITLE
What's the answer?

### ISSUE THREAD

**Issue by nyngwang** [arzg/website#16]
Does `QOS_CLASS_IMMIGRATION` mean `blog` so I'm here? From the developer tool console.

**Comment by lunacookies** [comment]
No. I’ll give you a hint – try opening that QoS URL and see where that leads you :)

**Comment by thisisnotatrash** [comment]
I'm stuck finding the hint in the text :/

any help ? (or should I join the navy ?)

**Comment by lunacookies** [comment]
Sounds like you got to the end :)
